apiVersion: v1
kind: ConfigMap
metadata:
  name: smartthingshop-config
data:
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka
  SERVICES_PRODUCT_URL: http://product-service:8082
  SERVICES_NOTIFICATION_URL: http://notification-service:8084
  REDIS_HOST: redis
  REDIS_PORT: "6379"
